apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: coder
  namespace: argocd-poc

spec:
  generators:
    - list:
        elements:
          - name: coder-1
            namespace: argocd-poc
            server: https://kubernetes.default.svc

  template:
    metadata:
      name: '{{name}}'

    spec:
      project: default

      source:
        repoURL: https://github.com/manojchappidi/coder-argocd.git
        targetRevision: main
        path: coder
        helm:
          valueFiles:
            - values.yaml

      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
