apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: coder
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: coder-1
            namespace: argocd-poc
            server: https://kubernetes.default.svc

  template:
    metadata:
      name: '{{name}}'

    spec:
      project: default

      sources:
        - repoURL: https://helm.coder.com/v2
          chart: coder
          targetRevision: 2.29.5
          helm:
            valueFiles:
              - $values/coder/values.yaml

        - repoURL: https://github.com/manojchappidi/coder-argocd.git
          targetRevision: main
          ref: values

      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
#          - ServerSideApply=true
