apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: coder
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: coder
            namespace: coder

  template:
    metadata:
      name: '{{name}}'

    spec:
      project: default

      source:
        repoURL: https://helm.coder.com/v2
        chart: coder
        targetRevision: 2.29.5

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
